version: "3"

services:
  mysql:
    image: mysql:8.0.38
    container_name: mysql-engineer-training
    ports:
      - "33061:3306"
    volumes:
      - ./mysql/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
